### ISSUE TITLE
(not an issue) adding ips to your ipset

### ISSUE THREAD

**Issue by XenocodeRCE** [TheBarret/Blacklist#1]
hello

i have 6444 bad ip in a txt file, from my service (rdp scan, and website crawlers) to share here if you want

issue is, some of them are ipv6, will it cause problem with that actual project ?

**Comment by TheBarret** [comment]
The db currently only holds ipv4, ipv6 is barely used for these things, thanks for the offer but i only log and save incidents on my own server.
